#!/bin/bash

jar cf mspac_tmp.jar -C PacMan-vs-Ghosts/target/classes . \
                     -C PacMan-vs-Ghosts-Agents/target/classes . \
                     -C PacMan-vs-Ghosts-Tournament/target/classes .

zip -d mspac_tmp.jar MyPacMan.class

mv -f mspac_tmp.jar mspac.jar
